// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfCs5_9jrMn8yqjRKJbvHjgG3GClt5nnM',
    appId: '1:700337866283:web:8790079ec32866f1e34c6e',
    messagingSenderId: '700337866283',
    projectId: 'chatapp-ad88a',
    authDomain: 'chatapp-ad88a.firebaseapp.com',
    storageBucket: 'chatapp-ad88a.appspot.com',
    measurementId: 'G-K7K8JE1HTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Fu9IUty5dHqF2jOL8qdWuVytEZi8xMI',
    appId: '1:700337866283:android:acc47ca3d18b2e26e34c6e',
    messagingSenderId: '700337866283',
    projectId: 'chatapp-ad88a',
    storageBucket: 'chatapp-ad88a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwUXin0CFe75GF-Z8zG414gSfZMfm0Gsc',
    appId: '1:700337866283:ios:4383b35a908be9b9e34c6e',
    messagingSenderId: '700337866283',
    projectId: 'chatapp-ad88a',
    storageBucket: 'chatapp-ad88a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwUXin0CFe75GF-Z8zG414gSfZMfm0Gsc',
    appId: '1:700337866283:ios:a72d9104e62d8197e34c6e',
    messagingSenderId: '700337866283',
    projectId: 'chatapp-ad88a',
    storageBucket: 'chatapp-ad88a.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
